version: '2'
services:

  common_db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres-data:
